apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: webapp
  
resources:
- ../../Base

patches:
- path: frontend-deployment-prod.yaml
- path: frontend-ingress-prod.yaml
- path: users-ingress-prod.yaml
- path: tasks-ingress-prod.yaml  
- path: tasks-deployment-persistentvolume_prod.yaml
#images:
  #- name: imrankhan28888/kub-demo-frontend:latest5
    #digest: sha256:ce85ee16d2195343f5ad2f483963ea55c17f3ade75a729c8c9d742ceff336b57
