apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
  
resources:
- ../../Base

patches:
- path: frontend-deployment-dev.yaml
- path: frontend-ingress-dev.yaml
- path: users-ingress-dev.yaml
- path: tasks-ingress-dev.yaml  
#images:
  #- name: imrankhan28888/kub-demo-frontend:latest5
    #digest: sha256:ce85ee16d2195343f5ad2f483963ea55c17f3ade75a729c8c9d742ceff336b57
