apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: webapp
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: imrankhan28888/kub-demo-auth:latestwebapp@sha256:3988cd70c34423b9478a324cffe9e52f3fbfc6bbc7a721c1f695c68f5f9db18b
          imagePullPolicy: Always