apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: webapp
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: imrankhan28888/kub-demo-frontend:latest5@sha256:0db04d5345a1194fa4d5e524649cd72e11c3b008fd92f7a76b19a5fa4caf39af
          imagePullPolicy: Always
