apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
  namespace: webapp
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: imrankhan28888/kub-demo-tasks:latestwebapp@sha256:84dfb8b950b299392a1d19258e33c5902c62442c9b541cafd150258460e25a3f
          imagePullPolicy: Always
          volumeMounts:
          - name: volv
            mountPath: /app/tasks 
          env:
            - name: AUTH_ADDRESS
              # value: "10.99.104.252"
              value: "auth-service.webapp"
            - name: TASKS_FOLDER
              value: tasks
      volumes:
      - name: volv
        persistentVolumeClaim:
          claimName: longhorn-volv-pvc
