name: Build and Publish image to Docker Hub-Prod
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/**'
      - 'kubernetes/**'  
  #[workflow_dispatch]
  
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build ./kub-network-07-finished-Minikube/kub-network-07-finished-Minikube/frontend/ -t imrankhan28888/kub-demo-frontend:latest5
          #docker build ./kub-network-07-finished-Minikube/kub-network-07-finished-Minikube/tasks-api/ -t imrankhan28888/kub-demo-tasks:latestwebapp
          #docker build ./kub-network-07-finished-Minikube/kub-network-07-finished-Minikube/users-api/ -t imrankhan28888/kub-demo-users:latestwebapp
          #docker build ./kub-network-07-finished-Minikube/kub-network-07-finished-Minikube/auth-api/ -t imrankhan28888/kub-demo-auth:latestwebapp
          
      - name: Login to docker Hub
        run: |
          docker login -u imrankhan28888 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push imrankhan28888/kub-demo-frontend:latest5
          #docker push imrankhan28888/kub-demo-tasks:latestwebapp
          #docker push imrankhan28888/kub-demo-users:latestwebapp
          #docker push imrankhan28888/kub-demo-auth:latestwebapp
