name: Build and Publish image to Docker Hub
on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build ./kub-network-07-finished-Minikube/kub-network-07-finished-Minikube/frontend/ -t imrankhan28888/kub-demo-frontend:latest5
      - name: Login to docker Hub
        run: |
          docker login -u imrankhan28888 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push imrankhan28888/kub-demo-frontend:latest5
